name: scene_env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - transformers
    - ultralytics
    - opencv-python
    - matplotlib
    - open3d
    - timm
    - einops
    - git+https://github.com/isl-org/MiDaS.git
